# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36bf4c61c9242182830a4345574846becb5f0a92035d1cdd588ca392ba17650ce7ba5b4b4be76b3abe810e2c56d4996668022dd498d7843ad10c60662e362f2e

test:
  secret_key_base: eb43b37d58c89067c6170e104523fb9cd0b8a81226cd9f7bfb7742239363070bcb4f5c69508cc05fabe90d9d54ede1b499c72644c8eb3d630e67d51e4372f223

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
